theme: jekyll-theme-slate
title: Welcome to the homepage of ChristianBedwell
description: This is the homepage of ChristianBedwell, where you will find all contributions to my Software Specifications project.
